layout_spectrum: 0.8877551
color:
  saturation: 0.3748943
  lightness: 0.3047867
  brandStrength: 0.2150833
  rhythmicContrast: 0.8678063
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.9125386
name: 'Integral diamond '
